@ECHO OFF

:loop
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 2
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 10
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 300
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 300
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 600
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
timeout 300
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
Start https://media.tenor.com/rC2iPMjyF48AAAAd/bingus-sphynx-cat.gif
goto loop
